### PR TITLE
Add draft of assembly questions

### PR DESCRIPTION
**Pull request by powerjg**
Signed-off-by: Jason Lowe-Power <jason@lowepower.com>

### CODE REVIEW

**Comment by powerjg** [comment]
Hey Bradley and Justin,

Here's a draft of the assembly questions. Let me know what you think.

@animalvgamer will you make sure you can do one or two of the questions to make sure I haven't made it too hard. If you think the students here will struggle with this, please let me know!

Also, I'm debating whether this should be *in the lab1.rst* or if it should just be linked. I want to make sure the students actually do this part of the assignment, but I would rather it be in a separate file. It's up to you when it's integrated, I guess.

**Comment by animalvgamer** [comment]
As far as the questions go, I like the style of them. They are straightforward, and are easy to grade as well. I think they may be a little more challenging than necessary for such an early assignment though, as my original impression of what you had described was just to make sure that students were still aware of how instructions worked in the context of assembly, which the students should have completed before taking this class. I do believe that students should be able to follow the code correctly given enough time.

The questions are still, I think, fairly significantly on the difficult side, especially for a first assignment.

I might consider either adding a note within the assignment for small things like "j $31" being equivalent to ret and $0 being a constant 0, as those might not be obvious to someone who has not used MIPS before. Additionally, I also had issues with "la" at first without needing to just infer from context, as it was not an instruction included within the linked documentation, as far as I could tell. These issues might  alternatively be avoided by using small blocks of assembly within each question instead of doing it entirely as functions, and perhaps avoiding $0?

P.S. There's a line in the ARM code, "add r3, r1, r3, lsl #2" which looks like there's a missing newline somewhere, but my ARM isn't strong enough to be sure, haha

**Comment by animalvgamer** [comment]
As a response to your last consideration, I also think that having this as a separate document will make it easier to maintain. We could have it as a separate assignment too, perhaps due at the same time as Lab 1, instead of tying them that closely. This seems more like a written assignment that won't have much to touch on in interactive grading either way.

Heck, if it was short enough, we might even have it as a diagnostic quiz type item like what we had at the beginning of 201A. In that case, difficulty would be even less of an issue as students would have less pressure to know their material from a previous class perfectly, vs just practicing their past experience within the new architecture. I suppose the option is dependent on if the goal is to press students to use and practice their ability to read and understand assembly, or just to check that they know it and can practice it before executing on it in "hardware."

**Comment by jlperona** [comment]
I didn't try any of the questions, but I like the style. I think the difficulty of the questions should be fine, though it will take some time for students to go through it. ~~I'm a little bit worried about the length of the assignment more than anything, but they have 2 weeks, and the first part in Logisim takes very little time. I would lean towards eliminating one of the MIPS questions, but I'm not going to push for it.~~

I'm fine with it being a separate file as long as there's warnings within the lab file about there being another part to the assignment. ~~Making this a separate assignment for them to turn in would help remind them, we just need to be careful about the points assigned. I'd like to touch on it in interactive grading if possible, but that's not a priority.~~

@animalvgamer Maybe Sean's MIPS guide that he had would be more useful? I think it includes `la` on there. It's somewhere in the Dropbox for the old Lab 2, I could probably dig it out.

**Comment by jlperona** [comment]
I just saw #5 and I agree, make this optional but highly recommended.

**Comment by powerjg** [comment]
I'm merging this as is. If you have any other comments, feel free to open another PR.

**Pull request merged**
